### ISSUE TITLE
Not working in Ubuntu 21.04

### ISSUE THREAD

**Issue by pianist2189** [kanhavishva/RMD160-Sort#1]
Hi! How to compile this program on Ubuntu? Thanks!

**Comment by secp8x32** [comment]
g++ -std=c++11 RMD160-Sort.cpp -o RMD160-Sort

**Comment by pianist2189** [comment]
> g++ -std=c++11 RMD160-Sort.cpp -o RMD160-Sort

g++ -std=c++11 RMD160-Sort.cpp -o RMD160-Sort
RMD160-Sort.cpp: In function ‘void sort_file(const char*, const char*)’:
RMD160-Sort.cpp:196:2: error: ‘_fseeki64’ was not declared in this scope
  _fseeki64(fd, 0, SEEK_END);
  ^~~~~~~~~
RMD160-Sort.cpp:196:2: note: suggested alternative: ‘fseeko64’
  _fseeki64(fd, 0, SEEK_END);
  ^~~~~~~~~
  fseeko64
RMD160-Sort.cpp:197:18: error: ‘_ftelli64’ was not declared in this scope
  int64_t TOTAL = _ftelli64(fd);
                  ^~~~~~~~~
RMD160-Sort.cpp:197:18: note: suggested alternative: ‘ftello64’
  int64_t TOTAL = _ftelli64(fd);
                  ^~~~~~~~~
                  ftello64
RMD160-Sort.cpp:201:9: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
  printf("Total addresses: %llu\n", N);
         ^~~~~~~~~~~~~~~~~~~~~~~~~  ~
RMD160-Sort.cpp:211:9: warning: too many arguments for format [-Wformat-extra-args]
  printf("Reading data...\n", N);
         ^~~~~~~~~~~~~~~~~~~
RMD160-Sort.cpp:214:9: warning: too many arguments for format [-Wformat-extra-args]
  printf("Reading data complete\n", N);
         ^~~~~~~~~~~~~~~~~~~~~~~~~
RMD160-Sort.cpp:216:9: warning: too many arguments for format [-Wformat-extra-args]
  printf("Sorting data...\n", N);
         ^~~~~~~~~~~~~~~~~~~
RMD160-Sort.cpp:219:9: warning: too many arguments for format [-Wformat-extra-args]
  printf("Sorting data complete\n", N);
         ^~~~~~~~~~~~~~~~~~~~~~~~~
RMD160-Sort.cpp:221:9: warning: too many arguments for format [-Wformat-extra-args]
  printf("Saving data...\n", N);
         ^~~~~~~~~~~~~~~~~~
RMD160-Sort.cpp:223:9: warning: too many arguments for format [-Wformat-extra-args]
  printf("Saving data complete\n", N);
         ^~~~~~~~~~~~~~~~~~~~~~~~

**Comment by pianist2189** [comment]
Please write this for linux! thanks!
